FROM xhofe/alist:latest
LABEL MAINTAINER="i@nn.ci"
WORKDIR /opt/alist/

ARG PORT
ARG DB_TYPE
ARG DB_HOST
ARG DB_PORT
ARG DB_USER
ARG DB_PASS
ARG DB_NAME
ARG DB_TABLE_PREFIX

ENV PORT=$PORT
ENV DB_TYPE=$DB_TYPE
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_USER=$DB_USER
ENV DB_PASS=$DB_PASS
ENV DB_NAME=$DB_NAME
ENV DB_TABLE_PREFIX=$DB_TABLE_PREFIX

EXPOSE 5244

CMD [ "./alist", "server", "--no-prefix" ]
